#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate cloudcannon.config.yml from the content/*.json shape.

Same philosophy as gen_tina.py (which it replaces): the editor schema is
derived from the content files, so it can never drift from what build.py
actually reads. Run after any structural content change.

CloudCannon reads this file from the repo root of the SITE (source.path
below handles the site/ prefix). Each content JSON becomes a data file with
per-field _inputs giving humanized labels that preview the current text.
"""
import json, os, re

D = os.path.dirname(os.path.abspath(__file__))

PAGE_LABEL = {
    'home': 'Homepage', 'history': 'History page', 'story': 'Our Story page',
    'itinerary': 'Itinerary page', 'header': 'Site header (all pages)',
    'footer': 'Site footer (all pages)', 'discover': 'Discover Curaçao cards',
}
GROUPTRIP_FIELD_LABEL = {
    'slug': 'URL name (lowercase, hyphens; becomes /groups/<name>/)',
    'title': 'Page headline',
    'subtitle': 'Subtitle',
    'congregation': 'Congregation',
    'leader': 'Trip leader (e.g. Rabbi …)',
    'leader_image': 'Trip leader portrait (optional, shown on PDF cover)',
    'dates': 'Dates',
    'duration': 'Duration',
    'group_size': 'Group size',
    'start_finish': 'Start / finish',
    'pace': 'Pace',
    'accommodation': 'Accommodation',
    'price_note': 'Price note',
    'hero_image': 'Hero image',
    'intro': 'Intro',
    'highlights': 'Highlights',
    'included': 'What is included',
    'not_included': 'What is not included',
    'vignettes': 'Editorial vignettes',
    'itinerary': 'Itinerary',
    'gallery': 'Photo gallery',
    'form_intro': 'Inquiry form intro',
    'notify_note': 'Notify note',
    'contact_email': 'Contact email (shown on the PDF)',
    'contact_phone': 'Contact phone (shown on the PDF)',
    'pdf': 'Trip details PDF (path, optional)',
    'published': 'Published',
}
GROUPTRIP_TEXTAREA = {'intro', 'highlights', 'included', 'not_included', 'form_intro', 'notify_note'}
GROUPTRIP_COMMENT = {
    'highlights': 'One item per line',
    'included': 'One item per line',
    'not_included': 'One item per line',
    'pdf': 'Leave blank to hide the PDF download button',
    'published': 'Untick to hide the page from the website',
}
GROUP_LABEL = {
    'home': 'General', 'top': 'Hero', 'doors': 'Three doorways',
    'whatwedo': 'What we do', 'beginband': 'Begin your journey',
    'defines': 'What defines us', 'howweplan': 'How we plan',
    'discover': 'Discover Curaçao', 'voices': 'Testimonials',
    'contact': 'Contact', 'lightbox': 'Footer & photo viewer',
    'header': 'Header', 'footer': 'Footer', 'subhero': 'Page banner',
    'history': 'Essay', 'story': 'Story', 'itinerary': 'Itinerary',
    'namepanel': 'Name panel', 'bio': 'Founder bios',
}
FIELD_LABEL = {
    'h1': 'Headline', 'h2': 'Headline', 'h3': 'Subheading', 'h4': 'Subheading',
    'p': 'Paragraph', 'blockquote': 'Quote', 'cite': 'Attribution',
    'span': 'Small text', 'a': 'Link text', 'button': 'Button',
    'figcaption': 'Caption', 'li': 'List item', 'label': 'Form label',
    'em': 'Emphasis', 'strong': 'Bold text', 'text': 'Text',
    'summary': 'Summary', 'option': 'Option', 'td': 'Cell', 'th': 'Heading',
}

def yq(s):
    """Quote a string for YAML."""
    return json.dumps(s, ensure_ascii=False)

def flabel(field):
    """Stable label. Deliberately contains no sample text: labels are baked at
    generation time, so any text in them goes stale the moment someone edits
    and then contradicts what is in the box."""
    m = re.match(r'([a-z]+?)(?:_([a-z_]+?))?_(\d+)$', field)
    tag, attr, n = (m.group(1), m.group(2), m.group(3)) if m else (field, None, '')
    base = FIELD_LABEL.get(tag, tag)
    if attr:
        base = 'Image description' if attr == 'alt' else attr.replace('_', ' ').title()
    return ('%s %s' % (base, n)).strip()

def fcomment(text):
    """Original wording, explicitly marked as history so a stale hint can never
    be mistaken for the current value."""
    if not text:
        return None
    hint = ' '.join(text.split())
    hint = (hint[:70] + '…') if len(hint) > 71 else hint
    return 'Originally: “%s”' % hint

out = ['''# Generated by gen_cloudcannon.py — do not edit by hand.
# Maps content/*.json (the build's editable copy) into CloudCannon's editor.
version: latest-v2

# CloudCannon edits and commits only; Cloudflare builds and hosts.
mode: headless
source: site

collections_config:
  content:
    path: content
    glob:
      - '*.json'
    name: Site copy
    icon: edit_note
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
  groups:
    path: content/groups
    glob:
      - '*.json'
      - '!.schema.json'
    name: Group Trips
    icon: groups
    create:
      path: '[relative_base_path]/{slug}.[ext]'
    schemas:
      default:
        path: .schema.json
    preview:
      title: '{title}'
      subtitle: '{dates}'

_inputs: {}

_structures:
  itinerary_day:
    values:
      - value:
          day: ''
          title: ''
          text: ''
          image: ''
          date: ''
          meals: ''
          overnight: ''
        _inputs:
          day:
            type: text
            label: 'Day (e.g. Day 1)'
          title:
            type: text
            label: 'Day title'
          text:
            type: textarea
            label: 'Day description'
          image:
            type: image
            label: 'Day photo (optional)'
          date:
            type: text
            label: 'Date (optional, e.g. Sun, March 14)'
          meals:
            type: text
            label: 'Meals included (optional, e.g. B, L, D)'
          overnight:
            type: text
            label: 'Overnight location (optional)'
  vignette:
    values:
      - value:
          title: ''
          text: ''
          image: ''
        _inputs:
          title:
            type: text
            label: 'Vignette headline'
          text:
            type: textarea
            label: 'Vignette copy'
          image:
            type: image
            label: 'Vignette photo'

paths:
  uploads: assets/img
''']

# per-file _inputs keyed with the file scope so labels land on the right page
finputs = []
for fn in sorted(os.listdir(os.path.join(D, 'content'))):
    if not fn.endswith('.json'):
        continue
    page = fn[:-5]
    data = json.load(open(os.path.join(D, 'content', fn), encoding='utf-8'))
    finputs.append((page, data))

# CloudCannon reads per-file settings from the config's _inputs with globs is
# not supported; instead we emit one _inputs block per key path, scoped by
# file via `_inputs` in a `file_config` entry (v2 feature).
fc = ['file_config:']
for page, data in finputs:
    fc.append('  - glob: content/%s.json' % page)
    fc.append('    _inputs:')
    for group, fields in data.items():
        glabel = GROUP_LABEL.get(group, group.title())
        fc.append('      %s:' % group)
        fc.append('        type: object')
        fc.append('        label: %s' % yq(glabel))
    for group, fields in data.items():
        for field, text in fields.items():
            comp = 'textarea' if len(text or '') > 80 else 'text'
            fc.append('      %s.%s:' % (group, field))
            fc.append('        type: %s' % comp)
            fc.append('        label: %s' % yq(flabel(field)))
            c = fcomment(text)
            if c:
                fc.append('        comment: %s' % yq(c))

# group-trip landing pages: one uniform schema, so a single file_config
# block (rather than one per file, as content/*.json needs) covers every
# item in the collection.
fc.append('  - glob: content/groups/*.json')
fc.append('    _inputs:')
for field, label in GROUPTRIP_FIELD_LABEL.items():
    fc.append('      %s:' % field)
    if field in ('hero_image', 'leader_image'):
        fc.append('        type: image')
    elif field == 'itinerary':
        fc.append('        type: array')
        fc.append('        options:')
        fc.append('          structures: itinerary_day')
    elif field == 'vignettes':
        fc.append('        type: array')
        fc.append('        options:')
        fc.append('          structures: vignette')
    elif field == 'gallery':
        fc.append('        type: array')
        fc.append('        options:')
        fc.append('          subtype: image')
    elif field == 'published':
        fc.append('        type: checkbox')
    elif field in GROUPTRIP_TEXTAREA:
        fc.append('        type: textarea')
    else:
        fc.append('        type: text')
    fc.append('        label: %s' % yq(label))
    if field in GROUPTRIP_COMMENT:
        fc.append('        comment: %s' % yq(GROUPTRIP_COMMENT[field]))

open(os.path.join(D, '..', 'cloudcannon.config.yml'), 'w', encoding='utf-8').write(
    out[0] + '\n' + '\n'.join(fc) + '\n')
print('cloudcannon.config.yml written: %d file blocks' % len(finputs))
