#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate cloudcannon.config.yml from the content/*.json shape.

Same philosophy as gen_tina.py (which it replaces): the editor schema is
derived from the content files, so it can never drift from what build.py
actually reads. Run after any structural content change.

CloudCannon reads this file from the repo root of the SITE (source.path
below handles the site/ prefix). Each content JSON becomes a data file with
per-field _inputs giving humanized labels that preview the current text.
"""
import json, os, re

D = os.path.dirname(os.path.abspath(__file__))

PAGE_LABEL = {
    'home': 'Homepage', 'history': 'History page', 'story': 'Our Story page',
    'itinerary': 'Itinerary page', 'header': 'Site header (all pages)',
    'footer': 'Site footer (all pages)', 'discover': 'Discover Curaçao cards',
}
GROUP_LABEL = {
    'home': 'General', 'top': 'Hero', 'doors': 'Three doorways',
    'whatwedo': 'What we do', 'beginband': 'Begin your journey',
    'defines': 'What defines us', 'howweplan': 'How we plan',
    'discover': 'Discover Curaçao', 'voices': 'Testimonials',
    'contact': 'Contact', 'lightbox': 'Footer & photo viewer',
    'header': 'Header', 'footer': 'Footer', 'subhero': 'Page banner',
    'history': 'Essay', 'story': 'Story', 'itinerary': 'Itinerary',
    'namepanel': 'Name panel', 'bio': 'Founder bios',
}
FIELD_LABEL = {
    'h1': 'Headline', 'h2': 'Headline', 'h3': 'Subheading', 'h4': 'Subheading',
    'p': 'Paragraph', 'blockquote': 'Quote', 'cite': 'Attribution',
    'span': 'Small text', 'a': 'Link text', 'button': 'Button',
    'figcaption': 'Caption', 'li': 'List item', 'label': 'Form label',
    'em': 'Emphasis', 'strong': 'Bold text', 'text': 'Text',
    'summary': 'Summary', 'option': 'Option', 'td': 'Cell', 'th': 'Heading',
}

def yq(s):
    """Quote a string for YAML."""
    return json.dumps(s, ensure_ascii=False)

def flabel(field, text):
    m = re.match(r'([a-z]+?)(?:_([a-z_]+?))?_(\d+)$', field)
    tag, attr, n = (m.group(1), m.group(2), m.group(3)) if m else (field, None, '')
    base = FIELD_LABEL.get(tag, tag)
    if attr:
        base = 'Image description' if attr == 'alt' else attr.replace('_', ' ').title()
    hint = text.strip().split('\n')[0]
    hint = (hint[:34] + '…') if len(hint) > 35 else hint
    return '%s %s — “%s”' % (base, n, hint)

out = ['''# Generated by gen_cloudcannon.py — do not edit by hand.
# Maps content/*.json (the build's editable copy) into CloudCannon's editor.
version: latest-v2

collections_config:
  content:
    path: content
    glob:
      - '*.json'
    name: Site copy
    icon: edit_note
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true

_inputs: {}

paths:
  uploads: assets/img
''']

# per-file _inputs keyed with the file scope so labels land on the right page
finputs = []
for fn in sorted(os.listdir(os.path.join(D, 'content'))):
    if not fn.endswith('.json'):
        continue
    page = fn[:-5]
    data = json.load(open(os.path.join(D, 'content', fn), encoding='utf-8'))
    finputs.append((page, data))

# CloudCannon reads per-file settings from the config's _inputs with globs is
# not supported; instead we emit one _inputs block per key path, scoped by
# file via `_inputs` in a `file_config` entry (v2 feature).
fc = ['file_config:']
for page, data in finputs:
    fc.append('  - glob: content/%s.json' % page)
    fc.append('    _inputs:')
    for group, fields in data.items():
        glabel = GROUP_LABEL.get(group, group.title())
        fc.append('      %s:' % group)
        fc.append('        type: object')
        fc.append('        label: %s' % yq(glabel))
    for group, fields in data.items():
        for field, text in fields.items():
            comp = 'textarea' if len(text) > 80 else 'text'
            fc.append('      %s.%s:' % (group, field))
            fc.append('        type: %s' % comp)
            fc.append('        label: %s' % yq(flabel(field, text)))

open(os.path.join(D, 'cloudcannon.config.yml'), 'w', encoding='utf-8').write(
    out[0] + '\n' + '\n'.join(fc) + '\n')
print('cloudcannon.config.yml written: %d file blocks' % len(finputs))
