#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate tina/config.ts from the content/*.json shape.

Run after tokenize_content.py (or whenever content structure changes) so the
editor schema can never drift from what the build actually reads.
"""
import json, os, re

D = os.path.dirname(os.path.abspath(__file__))

PAGE_LABEL = {
    'home': 'Homepage', 'history': 'History page', 'story': 'Our Story page',
    'itinerary': 'Itinerary page', 'header': 'Site header (all pages)',
    'footer': 'Site footer (all pages)', 'discover': 'Discover Curaçao cards',
}
GROUP_LABEL = {
    'home': 'General', 'top': 'Hero', 'doors': 'Three doorways',
    'whatwedo': 'What we do', 'beginband': 'Begin your journey',
    'defines': 'What defines us', 'howweplan': 'How we plan',
    'discover': 'Discover Curaçao', 'voices': 'Testimonials',
    'contact': 'Contact', 'lightbox': 'Photo viewer', 'header': 'Header',
    'footer': 'Footer', 'subhero': 'Page banner', 'history': 'Essay',
    'story': 'Story', 'itinerary': 'Itinerary', 'namepanel': 'Name panel',
}
FIELD_LABEL = {
    'h1': 'Headline', 'h2': 'Headline', 'h3': 'Subheading', 'h4': 'Subheading',
    'p': 'Paragraph', 'blockquote': 'Quote', 'cite': 'Attribution',
    'span': 'Small text', 'a': 'Link text', 'button': 'Button',
    'figcaption': 'Caption', 'li': 'List item', 'label': 'Form label',
    'em': 'Emphasis', 'strong': 'Bold text', 'text': 'Text',
    'summary': 'Summary', 'option': 'Option', 'td': 'Cell', 'th': 'Heading',
}

def flabel(field, text):
    m = re.match(r'([a-z]+?)(?:_([a-z_]+?))?_(\d+)$', field)
    tag, attr, n = (m.group(1), m.group(2), m.group(3)) if m else (field, None, '')
    base = FIELD_LABEL.get(tag, tag)
    if attr:
        base = 'Image description' if attr == 'alt' else attr.replace('_', ' ').title()
    hint = text.strip().split('\n')[0]
    hint = (hint[:34] + '…') if len(hint) > 35 else hint
    return '%s %s — “%s”' % (base, n, hint)

collections = []
for fn in sorted(os.listdir(os.path.join(D, 'content'))):
    if not fn.endswith('.json'):
        continue
    page = fn[:-5]
    data = json.load(open(os.path.join(D, 'content', fn), encoding='utf-8'))
    groups = []
    for group, fields in data.items():
        fdefs = []
        for field, text in fields.items():
            comp = ', ui: { component: "textarea" }' if len(text) > 80 else ''
            fdefs.append(
                '          { type: "string", name: %s, label: %s, required: true%s }'
                % (json.dumps(field), json.dumps(flabel(field, text)), comp))
        groups.append(
            '        { type: "object", name: %s, label: %s, fields: [\n%s\n        ] }'
            % (json.dumps(group), json.dumps(GROUP_LABEL.get(group, group.title())),
               ',\n'.join(fdefs)))
    collections.append('''    {
      name: %s,
      label: %s,
      path: "content",
      match: { include: %s },
      format: "json",
      ui: { allowedActions: { create: false, delete: false } },
      fields: [
%s
      ],
    }''' % (json.dumps(page), json.dumps(PAGE_LABEL.get(page, page.title())),
            json.dumps(page), ',\n'.join(groups)))

config = '''// Generated by gen_tina.py — do not edit by hand; edit content/*.json shape instead.
import { defineConfig } from "tinacms";

export default defineConfig({
  branch: process.env.HEAD || "main",
  clientId: process.env.TINA_CLIENT_ID || "c4a92e84-5acf-4dd9-a17b-42186d431031",
  token: process.env.TINA_TOKEN!,
  build: { outputFolder: "admin", publicFolder: "." },
  media: { tina: { mediaRoot: "assets/img", publicFolder: "." } },
  schema: { collections: [
%s
  ] },
});
''' % ',\n'.join(collections)

os.makedirs(os.path.join(D, 'tina'), exist_ok=True)
open(os.path.join(D, 'tina', 'config.ts'), 'w', encoding='utf-8').write(config)
print('tina/config.ts: %d collections' % len(collections))
